---
- name: Add Elastic GPG Key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic {{ elasticsearch_version }} repository
  apt_repository:
    repo: "{{ elasic_repo }}/{{ elasticsearch_version }}/apt stable main"
    state: present
    update_cache: true

- name: Stop heartbeat
  service:
    name: heartbeat
    state: stopped
  ignore_errors: true

- name: Install heartbeat
  apt:
    name: heartbeat
    state: "{{ beat_version }}"
  notify:
    - Stop heartbeat

- name: Create heartbeat configs directory
  file:
    path: '/etc/heartbeat/monitors.d'
    state: directory
    mode: 0755

- name: Add heartbeat configuration file
  template:
    src: 'etc/heartbeat/heartbeat.yml.tpl'
    dest: '/etc/heartbeat/heartbeat.yml'
    mode: 0600

- name: Add configuration files
  template:
    src: 'etc/heartbeat/monitors.d/{{ item }}.tpl'
    dest: '/etc/heartbeat/monitors.d/{{ item }}'
    mode: 0600
  loop:
    - checker-http.yml
    - checker-ssh.yml
  notify:
    - Restart heartbeat
